// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDo.SQLServer.Repository.Data;

#nullable disable

namespace ToDo.SQLServer.Repository.Migrations
{
    [DbContext(typeof(ToDoDbContext))]
    [Migration("20250121164931_my-first-migration")]
    partial class myfirstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDo.Core.UserCalendarAgregate.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserCalendarId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserCalendarId");

                    b.ToTable("TaskItem");
                });

            modelBuilder.Entity("ToDo.Core.UserCalendarAgregate.UserCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserCalendars");
                });

            modelBuilder.Entity("ToDo.Core.UserCalendarAgregate.TaskItem", b =>
                {
                    b.HasOne("ToDo.Core.UserCalendarAgregate.UserCalendar", null)
                        .WithMany("Tasks")
                        .HasForeignKey("UserCalendarId");
                });

            modelBuilder.Entity("ToDo.Core.UserCalendarAgregate.UserCalendar", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
